import "./../styles/globals.css";

import { Montserrat, Roboto } from "next/font/google";

import type { Metadata } from "next";
import SideBar from "../components/root-components/SideBar";
import { SocketProvider } from "../providers/socket-provider";
import { ThemeProvider } from "../providers/theme-provider";
import { Toaster } from "react-hot-toast";
import { getUserFromCookie } from "@/lib/user-auth";
import { redirect } from "next/navigation";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const montserrat = Montserrat({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();
  if (!user) redirect("/login");

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} ${montserrat.className} antialiased flex dark:bg-customBlack transition-all bg-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="bottom-right" reverseOrder={false} />
          <SocketProvider user={user}>
            <SideBar />
            {children}
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
