import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./../styles/globals.css";
import SideBar from "../components/root-components/SideBar";
import { ThemeProvider } from "../providers/theme-provider";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const montserrat = Montserrat({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} ${montserrat.className} antialiased flex dark:bg-customBlack transition-all bg-gray-50`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SideBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
